###SHADOW
shadow = true;
shadow-radius = 20
shadow-opacity = .75
shadow-offset-x = -7;
shadow-offset-y = -7;
# shadow-red = 0
# shadow-green = 0
# shadow-blue = 0
# shadow-color = "#000000"

###FADE
fading = true;
fade-in-step = 0.04;
fade-out-step = 0.05;
fade-delta = 1

###CORNERS
corner-radius = 20
round-borders = true

###BLUR
blur:
{
method = "dual_kawase";
size = 12;
strength = 4;
deviation = true;
kernel = "5x5gaussian";
}

###GENERAL
backend = "glx"
vsync = false;
detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;
use-damage = true;
log-level = "warn";

###RULES
wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
  dock = { shadow = false; clip-shadow-above = true; corner-radius = 0; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 0.8; }
  desktop = { corner-radius = 0; blur-background = false }
};

rules = (
{ match = "class_g = 'Rofi'";
  animations = (
    {
        triggers = [ "open", "show" ];
        duration = 0;
    },
    {
        triggers = [ "close", "hide" ];
        duration = 0;
    }
  );
},
{ match = "fullscreen"; corner-radius = 0; },
{ match = "_GTK_FRAME_EXTENTS@:c"; blur-background = false; shadow = false; },
{ match = "class_g = 'Polybar'"; shadow = false; corner-radius = 0; },
{ match = "name = 'Notification'"; shadow = false; },
{ match = "class_g = 'Conky'"; shadow = false; },
{ match = "class_g = 'Notify-osd'"; shadow = false; },
{ match = "class_g = 'Cairo-clock'"; shadow = false; },
{ match = "focused || group focused"; opacity = 1; frame-opacity = 0.1; },
{ match = "!focused && class_g != 'Polybar'" ; opacity = 0.85; dim = 0.05; frame-opacity = 0.1; }
)

###ANIMATIONS
animations = ({
	triggers = [ "geometry"];
	preset   = "geometry-change";
  duration = 0.2;
},
{
    triggers = ["open"];
    preset   = "appear";
    duration = 0.2;
    scale    = 0.2;
},
{
    triggers = ["close"];
    preset   = "disappear";
    duration = 0.2;
    scale    = 0.2;
}
)
##################END OF FILE picom.conf ###############################
