# Configure monitors
workspace 1 output $mm
workspace 2 output $mm
workspace 3 output $mm
workspace 4 output $mm
workspace 5 output $mm
workspace 6 output $mm
workspace 7 output $mm
workspace 8 output $mm
workspace 9 output $mm
workspace 10 output $mm
workspace 0 output $sm

# Define workspace vairables
set $ws0 "0"
set $ws1 "1:net"
set $ws2 "2:code"
set $ws3 "3:term"
set $ws4 "4:docs"
set $ws5 "5:chatgpt"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

